version: "1"

services:
  - type: web
    name: led-pixel-map-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_simple:app --timeout 120 --keep-alive 120 --workers 1
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
    healthCheckPath: /
